config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
	path('accounts/', include("django.contrib.auth.urls")),
	path('panel/', include("panel.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("home.urls")),
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
	path('', views.index, name="index"),
]

panel/urls.py
from django.urls import path
from . import views

app_name = "panel"
urlpatterns = [
	path("home/", views.index, name="home"),
	path("profile/", views.profile, name="profile"),
	path("profile/avatar/", views.update_remove_avatar, name="update_remove_avatar"),

	# users
	path("users/", views.users_list, name="users_list"),
	path("users/create/", views.create_user, name="create_user"),
	path("users/update/<int:id>/", views.update_user, name="update_user"),
	path("users/delete/<int:id>/", views.delete_user, name="delete_user"),

	# management
	path("admin/users/", views.management_users_list, name="management_users_list"),
	path("admin/users/create/", views.create_staff_user, name="create_staff_user"),
	path("admin/users/update/<int:id>/", views.update_staff_user, name="update_staff_user"),
	path("admin/users/delete/<int:id>/", views.delete_staff_user, name="delete_staff_user"),
	path("admin/roles/", views.roles_list, name="roles_list"),
	path("admin/roles/create/", views.create_role, name="create_role"),
	path("admin/roles/update/<int:id>/", views.update_role, name="update_role"),
	path("admin/roles/delete/<int:id>/", views.delete_role, name="delete_role"),
	path("admin/categories/", views.categories_list, name="categories_list"),
	path("admin/categories/create/", views.create_category, name="create_category"),
	path("admin/categories/update/<int:id>/", views.update_category, name="update_category"),
	path("admin/categories/delete/<int:id>/", views.delete_category, name="delete_category"),
	path("settings/website/", views.website_settings, name="website_settings"),
	path("settings/aboutus/", views.aboutus_settings, name="aboutus_settings"),
	path("settings/contactus/", views.contactus_settings_list, name="contactus_settings_list"),
]

panel/models.py
import os
from django.db import models
from django.core.validators import MinLengthValidator
from django.template.defaultfilters import truncatechars
from django.utils.translation import gettext as _
from utils.general_model import GeneralModel
from ckeditor_uploader.fields import RichTextUploadingField

def get_logo_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'logo.{ext}'
    return os.path.join(f'logo/', filename)

def get_favicon_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'favicon.{ext}'
    return os.path.join(f'logo/', filename)


class Category(GeneralModel):
	name = models.CharField(
		max_length=250,
		verbose_name=_("Name"),)
	slug = models.SlugField(
		max_length=250,
		unique=True,
		verbose_name=_("Slug"),)
	parent = models.ForeignKey(
		'self',
		on_delete=models.SET_NULL,
		default=None,
		null=True,
		blank=True,
		related_name="children",
		verbose_name=_("Parent"),)

	class Meta:
		verbose_name = _("Category")
		verbose_name_plural = _("Categories")

	def __str__(self):
		return self.name


class Settings(GeneralModel):
	name = models.CharField(
		default="admin panel",
		max_length=250,
		verbose_name=_("Name"),)
	url = models.URLField(
		null=True,
		blank=True,
		default="site.com",
		verbose_name=_("website url"),)
	logo = models.ImageField(
		upload_to=get_logo_path,
		default="logo/logo.png",
		null=True,
		blank=True,
		verbose_name=_("Logo"),)
	favicon = models.ImageField(
		upload_to=get_favicon_path,
		default="logo/favicon.ico",
		null=True,
		blank=True,
		verbose_name=_("Favicon"),)
	slug = models.SlugField(
		max_length=250,
		unique=True,
		default="settings",
		verbose_name=_("Slug"),)

	class Meta:
		verbose_name = _("Setting")
		verbose_name_plural = _("Settings")

	def __str__(self):
		return self.name


class AboutUs(GeneralModel):
	text = RichTextUploadingField(
		null=True,
		blank=True,
		verbose_name=_("Text"))
	terms = RichTextUploadingField(
		null=True,
		blank=True,
		verbose_name=_("Terms and Conditions"))
	email = models.EmailField(
		default="info@site.com",
		null=True,
		blank=True,
		verbose_name=_("Email"),)
	phone = models.CharField(
		max_length=13,
		default="+989121231234",
		null=True,
		blank=True,
		verbose_name=_("Phone"),)
	slug = models.SlugField(
		max_length=250,
		unique=True,
		default="aboutus",
		verbose_name=_("Slug"),)
	


	class Meta:
		verbose_name = _("About Us")
		verbose_name_plural = _("About Us")

	def __str__(self):
		return "About Us"

	@property
	def short_text(self):
		return truncatechars(self.text, 100)


class ContactUs(GeneralModel):
	full_name = models.CharField(max_length=128,
								 verbose_name=_("Full name"),)
	email = models.EmailField(
		verbose_name=_("Email"),)
	text = models.TextField(
		verbose_name=_("Text"))
	phone = models.CharField(max_length=13,
							 validators=[MinLengthValidator(10)],
							 blank=True,
							 null=True,
							 verbose_name=_("Phone"),)

	class Meta:
		verbose_name = _("Contact Us")
		verbose_name_plural = _("Contact Us")

	def __str__(self):
		return f"{self.full_name} -> {self.email}"

	@property
	def short_text(self):
		return truncatechars(self.text, 100)

panel/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from accounts.models import CustomUser
from .models import (
	Category,
	Settings,
	AboutUs,
	ContactUs,
)


class ProfileForm(forms.ModelForm):
	address = forms.CharField(widget=forms.Textarea(attrs={"rows":2}),
							  required=False,)
	
	class Meta:
		model = CustomUser
		fields = ("nick_name", "full_name", "phone",
				  "email", "address", "avatar",)


class CreateStaffUserForm(UserCreationForm):
	password2 = None
	roles = forms.ModelChoiceField(queryset=Group.objects.all(), required=False)
	
	class Meta:
		model = CustomUser
		fields = ("email", "full_name", "roles",)


class UpdateStaffUserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput(),
							   required=False,)
	address = forms.CharField(widget=forms.Textarea(attrs={"rows":2}),
							  required=False,)
	roles = forms.ModelChoiceField(queryset=Group.objects.all(), required=False)

	class Meta:
		model = CustomUser
		fields = ("nick_name", "full_name", "password", "phone",
				  "email", "address", "avatar", "is_active", "roles",)


class CreateUserPanelForm(UserCreationForm):
	password2 = None

	class Meta:
		model = CustomUser
		fields = ("full_name", "email", "avatar",)


class UpdateUserPanelForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput(),
							   required=False,)
	address = forms.CharField(widget=forms.Textarea(attrs={"rows":2}),
							  required=False,)

	class Meta:
		model = CustomUser
		fields = ("nick_name", "full_name", "password", "phone",
				  "email", "address", "avatar", "is_active",)


class PermissionPanelForm(forms.ModelForm):
	permissions = None
	management = forms.BooleanField(required=False,)
	settings = forms.BooleanField(required=False,)
	category = forms.BooleanField(required=False,)
	users = forms.BooleanField(required=False,)
	
	class Meta:
		model = Group
		fields = ['name', 'management', 'settings',
				  'category', 'users',]

class CategoryPanelForm(forms.ModelForm):

	class Meta:
		model = Category
		fields = ["name", "parent", "slug",]


class SettingsPanelForm(forms.ModelForm):

	class Meta:
		model = Settings
		fields = ["name", "url", "logo", "favicon"]


class AboutUsPanelForm(forms.ModelForm):

	class Meta:
		model = AboutUs
		fields = ["text", "terms", "email", "phone",]


class ContactUsPanelForm(forms.ModelForm):

	class Meta:
		model = ContactUs
		fields = ["full_name", "email", "phone", "text",]


class UpdateAndRemoveAvatar(forms.ModelForm):
	remove_profile = forms.BooleanField(required=False,)
	avatar = forms.ImageField(widget=forms.FileInput())

	class Meta:
		model = CustomUser
		fields = ["avatar", "remove_profile"]

panel/templates/panel/management/role_list.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load jformat %}
{% load group_permissions %}

{% block css %}
<!-- Bootstrap css-->
<link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>

<!-- Icons css-->
<link href="{% static 'assets/plugins/web-fonts/icons.css' %}" rel="stylesheet"/>
<link href="{% static 'assets/plugins/web-fonts/font-awesome/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/plugins/web-fonts/plugin.css' %}" rel="stylesheet"/>

<!-- Style css-->
<link href="{% static 'assets/css-rtl/style/style.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/skins.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/dark-style.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/colors/default.css' %}" rel="stylesheet">

<!-- Color css-->
<link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css-rtl/colors/color.css' %}">

<!-- Select2 css -->
<link href="{% static 'assets/plugins/select2/css/select2.min.css' %}" rel="stylesheet">

<!-- Internal DataTables css-->
<link href="{% static 'assets/plugins/datatable/dataTables.bootstrap4.min-rtl.css' %}" rel="stylesheet" />
<link href="{% static 'assets/plugins/datatable/responsivebootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'assets/plugins/datatable/fileexport/buttons.bootstrap4.min.css' %}" rel="stylesheet" />

<!-- Sidemenu css-->
<link href="{% static 'assets/css-rtl/sidemenu/sidemenu.css' %}" rel="stylesheet">

<!-- Toastr css -->
<link href="{% static 'assets/plugins/toastr/toastr.min.css' %}" rel="stylesheet">

<!-- Switcher css-->
<link href="{% static 'assets/switcher/css/switcher-rtl.css' %}" rel="stylesheet">
<link href="{% static 'assets/switcher/demo.css' %}" rel="stylesheet">
{% endblock css %}

{% block title %}
نقش‌ها
{% endblock title %}

{% block main-inner-content %}
<!-- Page Header -->
<div class="page-header">
	<div>
		<h2 class="main-content-title tx-24 mg-b-5"> مدیریت </h2>
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{% url 'panel:home' %}">خانه</a></li>
			<li class="breadcrumb-item active" aria-current="page">مدیریت</li>
			<li class="breadcrumb-item active" aria-current="page">نقش‌ها</li>
		</ol>
	</div>
</div>


<div class="row">
	<div class="col-lg-12">
		<div class="card custom-card overflow-hidden">
			<div class="card-body">
				<div>
					<button class="btn btn-primary mb-3" data-toggle="modal" data-target="#modal-create">ایجاد نقش جدید</button>
					<!-- Create Modal -->
					<div class="modal fade" id="modal-create">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<h4 class="modal-title">ساخت نقش جدید</h4>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<!-- form start -->
									<form  method="POST" action="{% url 'panel:create_role' %}" >
										{% csrf_token %}
										<div class="card-body">
											<div class="form-group">
												<label for="id_name">نام نقش</label>
												{% render_field create_group_form.name class+="form-control" placeholder="نام نقش را وارد کنید" required="required" %}
											</div>
											<div class="form-group">
												<label>سطوح دسترسی</label>
												<div class="row">
													<div class="col">
														<label class="ckbox">
															{% render_field create_group_form.management %}
															<span>مدیریت</span>
														</label>
													</div>
													<div class="col">
														<label class="ckbox">
															{% render_field create_group_form.users %}
															<span>مدیریت کاربران</span>
														</label>
													</div>
												</div>
												<div class="row">
													<div class="col">
														<label class="ckbox">
															{% render_field create_group_form.category %}
															<span>دسته بندی</span>
														</label>
													</div>
													<div class="col">
														<label class="ckbox">
															{% render_field create_group_form.settings %}
															<span>تنظیمات سایت</span>
														</label>
													</div>
												</div>
											</div>
										</div>
										<!-- /.card-body -->

										<div class="card-footer">
											<button type="submit" class="btn btn-primary">ایجاد</button>
										</div>
									</form>
								</div>
							</div>
							<!-- /.modal-content -->
						</div>
						<!-- /.modal-dialog -->
					</div>
				</div>
				<div class="table-responsive">
					<table id="table" class="table table-bordered table-striped text-center">
						<thead>
							<tr>
								<th>نام نقش</th>
								<th>عملیات</th>
							</tr>
						</thead>
						<tbody >
						{% for group in groups %}
							<tr>
								<td> {{ group.name }}</td>
								<td class="text-center">
									<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										<i class="fas fa-sliders-h"></i>
									</button>
									<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
										<button type="button" class="btn btn-success dropdown-item" data-toggle="modal" data-target="#modal-edit{{ group.id }}" style="padding-left:5px" ></i>ویرایش</button>
										<button type="button" class="dropdown-item" data-toggle="modal" data-target="#modal-delete{{ group.id }}" style="color:red;" >حذف</button>
									</div>
								</td>
							</tr>
							<!-- Delete Modal -->
							<div class="modal fade" id="modal-delete{{ group.id }}">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<h4 class="modal-title">حذف نقش</h4>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
											<h5>آیا در حذف نقش "{{ group.name }}" مطمئن هستید؟ </h5>
										</div>
										<div class="modal-footer justify-content-between">
											<button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
											<form action="{% url 'panel:delete_role' group.id %}" method="POST">
												{% csrf_token %}
												<button type="submit" class="btn btn-danger">حذف</button>
											</form>

										</div>
									</div>
									<!-- /.modal-content -->
								</div>
								<!-- /.modal-dialog -->
							</div>
							<!-- /.modal -->

							<!-- Change Modal -->
							<div class="modal fade" id="modal-edit{{ group.id }}">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<h4 class="modal-title">ویرایش نقش</h4>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
											<!-- form start -->
											<form  method="POST" action="{% url 'panel:update_role' group.id %}">
												{% csrf_token %}
												<div class="card-body">
													<div class="form-group">
														<label for="id_name">نام نقش</label>
														<input type="text" name="name" maxlength="150" class="form-control" placeholder="نام نقش را وارد کنید" value="{{ group.name }}" id="id_name" required="required" >
													</div>
													<div class="form-group">
														<label>سطوح دسترسی</label>
														<div class="row">
															<div class="col">
																<label class="ckbox">
																	<input {% if group|permissions_list:'can_manage_staff_users' %}checked{% endif %} type="checkbox" name="management" id="id_management">
																	<span>مدیریت</span>
																</label>
															</div>
															<div class="col">
																<label class="ckbox">
																	<input {% if group|permissions_list:'can_manage_simple_users' %}checked{% endif %} type="checkbox" name="users" id="id_users">
																	<span>مدیریت کاربران</span>
																</label>
															</div>
														</div>
														<div class="row">
															<div class="col">
																<label class="ckbox">
																	<input {% if group|permissions_list:'can_manage_categories' %}checked{% endif %} type="checkbox" name="category" id="id_categories">
																	<span>دسته بندی</span>
																</label>
															</div>
															<div class="col">
																<label class="ckbox">
																	<input {% if group|permissions_list:'can_manage_website_settings' %}checked{% endif %} type="checkbox" name="settings" id="id_settings">
																	<span>تنظیمات سایت</span>
																</label>
															</div>
														</div>
													</div>
												</div>
												<!-- /.card-body -->

												<div class="card-footer">
													<button type="submit" class="btn btn-primary">ویرایش</button>
												</div>
											</form>
										</div>
									</div>
									<!-- /.modal-content -->
								</div>
								<!-- /.modal-dialog -->
							</div>
							<!-- /.modal -->
						{% endfor %}

					</table>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock main-inner-content %}

{% block js %}
<!-- Jquery js-->
<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap js-->
<script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap-rtl.js' %}"></script>

<!-- Perfect-scrollbar js -->
<script src="{% static 'assets/plugins/perfect-scrollbar/perfect-scrollbar.min-rtl.js' %}"></script>

<!-- Sidemenu js -->
<script src="{% static 'assets/plugins/sidemenu/sidemenu-rtl.js' %}"></script>

<!-- Sidebar js -->
<script src="{% static 'assets/plugins/sidebar/sidebar-rtl.js' %}"></script>

<!-- Select2 js-->
<script src="{% static 'assets/plugins/select2/js/select2.min.js' %}"></script>

<!-- Internal Data Table js -->
<script src="{% static 'assets/plugins/datatable/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/jszip.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/pdfmake.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/vfs_fonts.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/buttons.html5.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/buttons.print.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/buttons.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/table-data.js' %}"></script>

<!-- Sticky js -->
<script src="{% static 'assets/js/sticky.js' %}"></script>

<!-- Toastr js -->
<script src="{% static 'assets/plugins/toastr/toastr.min.js' %}" ></script>
<script src="{% static 'assets/plugins/toastr/toastr-config.js' %}" ></script>

<!-- Custom js -->
<script src="{% static 'assets/js/custom.js' %}"></script>

<!-- Switcher js -->
<script src="{% static 'assets/switcher/js/switcher-rtl.js' %}"></script>
{% endblock js %}

{% block domready %}
<script>
    $(function () {
        $("#table").DataTable({
            "responsive": true,
            "autoWidth": false,
            "rtl" : true,
            "language": {
                "paginate": {
                    "previous": "قبلی",
                    "next" : "بعدی"
                },
                "sLengthMenu": "تعداد رکورد در صفحه _MENU_ ",
                "sSearch" : "جستجو:",
                "emptyTable":     "هیچ داده ای برای نمایش موجود نیست",
                "info":           "نمایش _START_ تا _END_ از _TOTAL_ رکورد",
                "infoEmpty":      "نمایش 0 تا 0 از 0 رکورد",

                "infoFiltered":   "(نتیجه جستجو بین _MAX_ رکورد)",
                "zeroRecords":    "اطلاعاتی مبنی بر جستجو شما موجود نیست...",
            },



        });
    });
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })

	$(function(){
		$("ul.pagination").css("justify-content", "start")
	});
</script>

{% include 'includes/messages.html' %}
{% endblock domready %}