config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
	path('accounts/', include("django.contrib.auth.urls")),
	path('panel/', include("panel.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("home.urls")),
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
	path('', views.index, name="index"),
]

panel/urls.py
from django.urls import path
from . import views

app_name = "panel"
urlpatterns = [
	path("home/", views.index, name="home"),
	path("profile/", views.profile, name="profile"),
	path("profile/avatar/", views.update_remove_avatar, name="update_remove_avatar"),

	# users
	path("users/", views.users_list, name="users_list"),
	path("users/create/", views.create_user, name="create_user"),
	path("users/update/<int:id>/", views.update_user, name="update_user"),
	path("users/delete/<int:id>/", views.delete_user, name="delete_user"),

	# management
	path("admin/users/", views.management_users_list, name="management_users_list"),
	path("admin/users/create/", views.create_staff_user, name="create_staff_user"),
	path("admin/users/update/<int:id>/", views.update_staff_user, name="update_staff_user"),
	path("admin/users/delete/<int:id>/", views.delete_staff_user, name="delete_staff_user"),
	path("admin/roles/", views.roles_list, name="roles_list"),
	path("admin/roles/create/", views.create_role, name="create_role"),
	path("admin/roles/update/<int:id>/", views.update_role, name="update_role"),
	path("admin/roles/delete/<int:id>/", views.delete_role, name="delete_role"),
	path("admin/categories/", views.categories_list, name="categories_list"),
	path("admin/categories/create/", views.create_category, name="create_category"),
	path("admin/categories/update/<int:id>/", views.update_category, name="update_category"),
	path("admin/categories/delete/<int:id>/", views.delete_category, name="delete_category"),
	path("settings/website/", views.website_settings, name="website_settings"),
	path("settings/aboutus/", views.aboutus_settings, name="aboutus_settings"),
	path("settings/contactus/", views.contactus_settings_list, name="contactus_settings_list"),
]

panel/models.py
import os
from django.db import models
from django.core.validators import MinLengthValidator
from django.template.defaultfilters import truncatechars
from django.utils.translation import gettext as _
from utils.general_model import GeneralModel
from ckeditor_uploader.fields import RichTextUploadingField

def get_logo_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'logo.{ext}'
    return os.path.join(f'logo/', filename)

def get_favicon_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'favicon.{ext}'
    return os.path.join(f'logo/', filename)


class Category(GeneralModel):
	name = models.CharField(
		max_length=250,
		verbose_name=_("Name"),)
	slug = models.SlugField(
		max_length=250,
		unique=True,
		verbose_name=_("Slug"),)
	parent = models.ForeignKey(
		'self',
		on_delete=models.SET_NULL,
		default=None,
		null=True,
		blank=True,
		related_name="children",
		verbose_name=_("Parent"),)

	class Meta:
		verbose_name = _("Category")
		verbose_name_plural = _("Categories")

	def __str__(self):
		return self.name


class Settings(GeneralModel):
	name = models.CharField(
		default="admin panel",
		max_length=250,
		verbose_name=_("Name"),)
	url = models.URLField(
		null=True,
		blank=True,
		default="site.com",
		verbose_name=_("website url"),)
	logo = models.ImageField(
		upload_to=get_logo_path,
		default="logo/logo.png",
		null=True,
		blank=True,
		verbose_name=_("Logo"),)
	favicon = models.ImageField(
		upload_to=get_favicon_path,
		default="logo/favicon.ico",
		null=True,
		blank=True,
		verbose_name=_("Favicon"),)
	slug = models.SlugField(
		max_length=250,
		unique=True,
		default="settings",
		verbose_name=_("Slug"),)

	class Meta:
		verbose_name = _("Setting")
		verbose_name_plural = _("Settings")

	def __str__(self):
		return self.name


class AboutUs(GeneralModel):
	text = RichTextUploadingField(
		null=True,
		blank=True,
		verbose_name=_("Text"))
	terms = RichTextUploadingField(
		null=True,
		blank=True,
		verbose_name=_("Terms and Conditions"))
	email = models.EmailField(
		default="info@site.com",
		null=True,
		blank=True,
		verbose_name=_("Email"),)
	phone = models.CharField(
		max_length=13,
		default="+989121231234",
		null=True,
		blank=True,
		verbose_name=_("Phone"),)
	slug = models.SlugField(
		max_length=250,
		unique=True,
		default="aboutus",
		verbose_name=_("Slug"),)
	


	class Meta:
		verbose_name = _("About Us")
		verbose_name_plural = _("About Us")

	def __str__(self):
		return "About Us"

	@property
	def short_text(self):
		return truncatechars(self.text, 100)


class ContactUs(GeneralModel):
	full_name = models.CharField(max_length=128,
								 verbose_name=_("Full name"),)
	email = models.EmailField(
		verbose_name=_("Email"),)
	text = models.TextField(
		verbose_name=_("Text"))
	phone = models.CharField(max_length=13,
							 validators=[MinLengthValidator(10)],
							 blank=True,
							 null=True,
							 verbose_name=_("Phone"),)

	class Meta:
		verbose_name = _("Contact Us")
		verbose_name_plural = _("Contact Us")

	def __str__(self):
		return f"{self.full_name} -> {self.email}"

	@property
	def short_text(self):
		return truncatechars(self.text, 100)

panel/views.py
from django.http import HttpResponse
from django.shortcuts import (
	render,
	redirect,
	get_object_or_404
)
from django.utils.translation import gettext as _
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import (
	Group,
	Permission,
)
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.forms import PasswordChangeForm
from accounts.models import CustomUser
from accounts.forms import CustomUserCreationForm
from panel.models import (
	Category,
	Settings,
	AboutUs,
	ContactUs,
)
from panel.forms import (
	AboutUsPanelForm,
	ProfileForm,
	CreateUserPanelForm,
	UpdateUserPanelForm,
	PermissionPanelForm,
	CategoryPanelForm,
	CreateStaffUserForm,
	UpdateStaffUserForm,
	SettingsPanelForm,
	UpdateAndRemoveAvatar,
)

@login_required
def index(request):
	return render(request,
				  "base.html",)


@login_required
def profile(request):
	user = CustomUser.objects.get(id=request.user.id)
	if request.method == "POST":
		profile_form = ProfileForm(request.POST, request.FILES, instance=user)
		if profile_form.is_valid():
			profile_form.save()
			message_text = _(f"پروفایل کاربری شما با موفقیت ویرایش شد.")
			messages.success(request, message_text)
			return redirect("panel:profile")
		else:
			message_text = _(f"ویرایش پروفایل کاربری با خطا شد.")
			messages.error(request, message_text)
			return redirect("panel:profile")
	else:
		profile_form = ProfileForm(instance=user)
		password_change_form = PasswordChangeForm(user=request.user)
		update_remove_avatar = UpdateAndRemoveAvatar(instance=request.user)

	return render(request,
				  "panel/profile.html",
				  {"profile_form": profile_form,
				   "password_change_form": password_change_form,
				   "update_remove_avatar": update_remove_avatar,})


@login_required
@permission_required("accounts.can_manage_simple_users", raise_exception=True,)
def users_list(request):
	users = CustomUser.objects.filter(is_superuser=False,
									  is_staff=False,)

	create_user_form = CreateUserPanelForm()
	update_user_from = UpdateUserPanelForm()
	return render(request,
				  "panel/users/list.html",
				  {"users": users,
				   "create_user_form": create_user_form,
				   "update_user_form": update_user_from,})

@login_required
@permission_required("accounts.can_manage_simple_users", raise_exception=True,)
def create_user(request):
	if request.method == "POST":
		form = CustomUserCreationForm(request.POST, request.FILES)
		if form.is_valid():
			email = form.cleaned_data.get("email")
			full_name = form.cleaned_data.get("full_name")
			user = form.save(commit=False)
			user.username = email
			user.nick_name = full_name
			user.save()
			message_text = _(f"کاربر «{ user.full_name }» با موفقیت ایجاد شد.")
			messages.success(request, message_text)
			return redirect("panel:users_list")
		else:
			message_text = _(f"ایجاد کاربر جدید با خطا مواجه شد.")
			messages.error(request, message_text)
			return redirect("panel:users_list")
	else:
		return HttpResponse("Method not allowed!")

@login_required
@permission_required("accounts.can_manage_simple_users", raise_exception=True,)
def update_user(request, id):
	user = get_object_or_404(CustomUser, id=id)

	if request.method == "POST":
		form = UpdateUserPanelForm(request.POST, request.FILES, instance=user)
		if form.is_valid():
			user = form.save(commit=False)
			if form.cleaned_data['password']:
				user.set_password(form.cleaned_data['password'])
			user.save()
			message_text = _(f"کاربر «{ user.full_name }» با موفقیت ویرایش شد.")
			messages.success(request, message_text)
			return redirect("panel:users_list")
		else:
			message_text = _(f"ویرایش کاربر «{ user.full_name }» با خطا مواجه شد.")
			messages.error(request, message_text)
			return redirect("panel:users_list")
	else:
		return HttpResponse("Method not allowed!")

@login_required
@permission_required("accounts.can_manage_simple_users", raise_exception=True,)
def delete_user(request, id):
	user = get_object_or_404(CustomUser, id=id)
	if request.method == "POST":
		user.delete()
		message_text = _(f"کاربر «{ user.full_name }» با موفقیت حذف شد.")
		messages.success(request, message_text)
		return redirect("panel:users_list")
	else:
		return HttpResponse("Method not allowed!")


@login_required
@permission_required("accounts.can_manage_staff_users", raise_exception=True,)
def management_users_list(request):
	if request.user.is_superuser:
		users = CustomUser.objects.filter(Q(is_staff=True) |
									  	  Q(is_superuser=True)).exclude(
											id=request.user.id)
	else:
		users = CustomUser.objects.filter(Q(is_staff=True) &
									  	  Q(is_superuser=False)).exclude(
											id=request.user.id)

	groups = Group.objects.all()
	create_staffuser_form = CreateStaffUserForm()
	update_staffuser_form = UpdateStaffUserForm()
	return render(request,
				  "panel/management/list.html",
				  {"users": users,
				   "groups": groups,
				   "create_staffuser_form": create_staffuser_form,
				   "update_staffuser_form": update_staffuser_form,})

@login_required
@permission_required("accounts.can_manage_staff_users", raise_exception=True,)
def create_staff_user(request):
	if request.method == "POST":
		form = CreateStaffUserForm(request.POST, request.FILES)
		if form.is_valid():
			email = form.cleaned_data.get("email")
			full_name = form.cleaned_data.get("full_name")
			user = form.save(commit=False)
			user.username = email
			user.nick_name = full_name
			user.is_staff = True
			user.save()
			message_text = _(f"کارمند «{ full_name }» با موفقیت ایجاد شد.")
			messages.success(request, message_text)
			return redirect("panel:management_users_list")
		else:
			message_text = _(f"ایجاد کارمند جدید با مواجه شد.")
			messages.error(request, message_text)
			return redirect("panel:management_users_list")
	else:
		return HttpResponse("Method not allowed!")


@login_required
@permission_required("accounts.can_manage_staff_users", raise_exception=True,)
def update_staff_user(request, id):
	user = get_object_or_404(CustomUser, id=id)

	if request.method == "POST":
		form = UpdateStaffUserForm(request.POST, request.FILES, instance=user)
		if form.is_valid():
			user = form.save(commit=False)
			if form.cleaned_data['password'] != '':
				user.set_password(form.cleaned_data['password'])
			if form.cleaned_data['roles']:
				group = form.cleaned_data['roles']
				user.groups.add(group)
			else:
				user.groups.clear()
			user.save()
			message_text = _(f"کارمند «{ user.full_name }» با موفقیت ویرایش شد.")
			messages.success(request, message_text)
			return redirect("panel:management_users_list")
		else:
			message_text = _(f"ویرایش کارمند «{ user.full_name }» با خطا مواجه شد.")
			messages.error(request, message_text)
			return redirect("panel:management_users_list")
	else:
		return HttpResponse("Method not allowed!")

@login_required
@permission_required("accounts.can_manage_staff_users", raise_exception=True,)
def delete_staff_user(request, id):
	user = get_object_or_404(CustomUser, id=id)

	if request.user.id == id:
		message_text = _(f"شما مجاز به حذف حساب کاربری خود نیستید.")
		messages.error(request, message_text)
		return redirect("panel:management_users_list")

	if request.method == "POST":
		user.delete()
		message_text = _(f"کارمند «{ user.full_name }» با موفقیت حذف شد.")
		messages.success(request, message_text)
		return redirect("panel:management_users_list")
	else:
		return HttpResponse("Method not allowed!")


@login_required
@permission_required("accounts.can_manage_staff_users", raise_exception=True,)
def roles_list(request):
	groups = Group.objects.all()
	create_group_form = PermissionPanelForm()
	update_group_form = PermissionPanelForm()
	return render(request,
				  "panel/management/role_list.html",
				  {"groups": groups,
				   "create_group_form": create_group_form,
				   "update_group_form": update_group_form,})

@login_required
@permission_required("accounts.can_manage_staff_users", raise_exception=True,)
def create_role(request):
	if request.method == "POST":
		form = PermissionPanelForm(request.POST)
		if form.is_valid():
			role_name = form.cleaned_data['name'].lower()
			role = Group.objects.filter(name=role_name)
			if role:
				return HttpResponse("role already exist!")
			group = form.save()

			# set permission to group
			if form.cleaned_data['management']:
				permission = Permission.objects.get(codename="can_manage_staff_users")
				group.permissions.add(permission)
			if form.cleaned_data['settings']:
				permission = Permission.objects.get(codename="can_manage_website_settings")
				group.permissions.add(permission)
			if form.cleaned_data['category']:
				permission = Permission.objects.get(codename="can_manage_categories")
				group.permissions.add(permission)
			if form.cleaned_data['users']:
				permission = Permission.objects.get(codename="can_manage_simple_users")
				group.permissions.add(permission)

			message_text = _(f"نقش «{ group.name }» با موفقیت ایجاد شد.")
			messages.success(request, message_text)
			return redirect("panel:roles_list")
		else:
			message_text = _(f"ایجاد نقش با خطا مواجه شد.")
			messages.error(request, message_text)
			return redirect("panel:roles_list")
	else:
		return HttpResponse("Method not allowed!")

@login_required
@permission_required("accounts.can_manage_staff_users", raise_exception=True,)
def update_role(request, id):
	group = get_object_or_404(Group, id=id)
	if request.method == "POST":
		form = PermissionPanelForm(request.POST, instance=group)
		if form.is_valid():
			group.name = form.cleaned_data['name']
			# set or remove permission to group
			permission = Permission.objects.get(codename="can_manage_staff_users")
			if form.cleaned_data['management']:
				group.permissions.add(permission)
			else:
				group.permissions.remove(permission)
			
			permission = Permission.objects.get(codename="can_manage_website_settings")
			if form.cleaned_data['settings']:

panel/templates/panel/categories/list.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load jformat %}

{% block css %}
<!-- Bootstrap css-->
<link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>

<!-- Icons css-->
<link href="{% static 'assets/plugins/web-fonts/icons.css' %}" rel="stylesheet"/>
<link href="{% static 'assets/plugins/web-fonts/font-awesome/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/plugins/web-fonts/plugin.css' %}" rel="stylesheet"/>

<!-- Style css-->
<link href="{% static 'assets/css-rtl/style/style.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/skins.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/dark-style.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/colors/default.css' %}" rel="stylesheet">

<!-- Color css-->
<link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css-rtl/colors/color.css' %}">

<!-- Select2 css -->
<link href="{% static 'assets/plugins/select2/css/select2.min.css' %}" rel="stylesheet">

<!-- Internal DataTables css-->
<link href="{% static 'assets/plugins/datatable/dataTables.bootstrap4.min-rtl.css' %}" rel="stylesheet" />
<link href="{% static 'assets/plugins/datatable/responsivebootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'assets/plugins/datatable/fileexport/buttons.bootstrap4.min.css' %}" rel="stylesheet" />

<!-- Sidemenu css-->
<link href="{% static 'assets/css-rtl/sidemenu/sidemenu.css' %}" rel="stylesheet">

<!-- Toastr css -->
<link href="{% static 'assets/plugins/toastr/toastr.min.css' %}" rel="stylesheet">

<!-- Switcher css-->
<link href="{% static 'assets/switcher/css/switcher-rtl.css' %}" rel="stylesheet">
<link href="{% static 'assets/switcher/demo.css' %}" rel="stylesheet">
{% endblock css %}

{% block title %}
دسته بندی‌ها
{% endblock title %}

{% block main-inner-content %}
<!-- Page Header -->
<div class="page-header">
	<div>
		<h2 class="main-content-title tx-24 mg-b-5"> دسته بندی‌ها </h2>
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{% url 'panel:home' %}">خانه</a></li>
			<li class="breadcrumb-item active" aria-current="page">دسته بندی‌ها</li>
			<li class="breadcrumb-item active" aria-current="page">دسته بندی</li>
		</ol>
	</div>
</div>


<div class="row">
	<div class="col-lg-12">
		<div class="card custom-card overflow-hidden">
			<div class="card-body">
				<div>
					<button class="btn btn-primary mb-3" data-toggle="modal" data-target="#modal-create">ایجاد دسته بندی جدید</button>
					<!-- Create Modal -->
					<div class="modal fade" id="modal-create">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<h4 class="modal-title">ساخت دسته بندی جدید</h4>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<!-- form start -->
									<form  method="POST" action="{% url 'panel:create_category' %}" >
										{% csrf_token %}
										<div class="card-body">
											<div class="form-group">
												<label for="id_name">نام</label>
												{% render_field create_category_form.name class+="form-control" placeholder="نام دسته بندی را وارد کنید" required="required" %}
											</div>
											<div class="form-group">
												<label for="id_slug">نشانک</label>
												{% render_field create_category_form.slug class+="form-control" placeholder="نشانک دسته بندی را وارد کنید" required="required" %}
											</div>
											<div class="form-group">
												<label for="id_parent">زیر دسته</label>
												{% render_field create_category_form.parent class+="form-control" %}
											</div>
										</div>
										<!-- /.card-body -->

										<div class="card-footer">
											<button type="submit" class="btn btn-primary">ایجاد</button>
										</div>
									</form>
								</div>
							</div>
							<!-- /.modal-content -->
						</div>
						<!-- /.modal-dialog -->
					</div>
				</div>
				<div class="table-responsive">
					<table id="table" class="table table-bordered table-striped text-center">
						<thead>
							<tr>
								<th>نام دسته بندی</th>
								<th>زیر دسته</th>
								<th>نشانک</th>
								<th>عملیات</th>
							</tr>
						</thead>
						<tbody >
						{% for category in categories %}
							<tr>
								<td>{{ category.name }}</td>
								<td>
									{% if category.parent %}
									{{ category.parent.name }}
									{% else %}
									-
									{% endif %}
								</td>
								<td>{{ category.slug }}</td>
								<td class="text-center">
									<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										<i class="fas fa-sliders-h"></i>
									</button>
									<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
										<button type="button" class="btn btn-success dropdown-item" data-toggle="modal" data-target="#modal-edit{{ category.id }}" >ویرایش</button>
										<button type="button" class="dropdown-item" data-toggle="modal" data-target="#modal-delete{{ category.id }}" style="color:red;" >حذف</button>
									</div>
								</td>

							</tr>
							<!-- Delete Modal -->
							<div class="modal fade" id="modal-delete{{ category.id }}">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<h4 class="modal-title">حذف دسته بندی</h4>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
											<h5>آیا در حذف "{{ category.name }}" مطمئن هستید؟ </h5>
										</div>
										<div class="modal-footer justify-content-between">
											<button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
											<form action="{% url 'panel:delete_category' category.id %}" method="POST">
												{% csrf_token %}
												<button type="submit" class="btn btn-danger">حذف</button>
											</form>

										</div>
									</div>
									<!-- /.modal-content -->
								</div>
								<!-- /.modal-dialog -->
							</div>
							<!-- /.modal -->

							<!-- Change Modal -->
							<div class="modal fade" id="modal-edit{{ category.id }}">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<h4 class="modal-title">ویرایش دسته بندی</h4>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
											<!-- form start -->
											<form  method="POST" action="{% url 'panel:update_category' category.id %}">
												{% csrf_token %}
												<div class="card-body">
													<div class="form-group">
														<label for="id_name">نام</label>
														<input type="text" name="name" maxlength="250" class="form-control" required="" placeholder="نام دسته بندی را وارد کنید" value="{{ category.name }}" id="id_name">
													</div>
													<div class="form-group">
														<label for="id_slug">نشانک</label>
														<input type="text" name="slug" maxlength="250" class="form-control" required="" placeholder="نشانک دسته بندی را وارد کنید" value="{{ category.slug }}" id="id_slug">
													</div>
													<div class="form-group">
														<label for="id_parent">زیر دسته</label>
														<select name="parent" class="form-control" id="id_parent">
															{% if category.parent %}
																<option value="">---------</option>
																<option value="{{ category.parent.id }}" selected="">{{ category.parent.name }}</option>
															{% else %}
																<option value="" selected="">---------</option>
															{% endif %}	
															{% for parent_category in categories %}
																{% if parent_category != category and parent_category != category.parent %}
																	<option value="{{ parent_category }}">{{ parent_category.name }}</option>
																{% endif %}
															{% endfor %}
														</select>
													</div>
												</div>
												<!-- /.card-body -->

												<div class="card-footer">
													<button type="submit" class="btn btn-primary">ویرایش</button>
												</div>
											</form>
										</div>
									</div>
									<!-- /.modal-content -->
								</div>
								<!-- /.modal-dialog -->
							</div>
							<!-- /.modal -->

						{% endfor %}

					</table>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock main-inner-content %}

{% block js %}
<!-- Jquery js-->
<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap js-->
<script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap-rtl.js' %}"></script>

<!-- Perfect-scrollbar js -->
<script src="{% static 'assets/plugins/perfect-scrollbar/perfect-scrollbar.min-rtl.js' %}"></script>

<!-- Sidemenu js -->
<script src="{% static 'assets/plugins/sidemenu/sidemenu-rtl.js' %}"></script>

<!-- Sidebar js -->
<script src="{% static 'assets/plugins/sidebar/sidebar-rtl.js' %}"></script>

<!-- Select2 js-->
<script src="{% static 'assets/plugins/select2/js/select2.min.js' %}"></script>

<!-- Internal Data Table js -->
<script src="{% static 'assets/plugins/datatable/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/jszip.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/pdfmake.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/vfs_fonts.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/buttons.html5.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/buttons.print.min.js' %}"></script>
<script src="{% static 'assets/plugins/datatable/fileexport/buttons.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/table-data.js' %}"></script>

<!-- Sticky js -->
<script src="{% static 'assets/js/sticky.js' %}"></script>

<!-- Toastr js -->
<script src="{% static 'assets/plugins/toastr/toastr.min.js' %}" ></script>
<script src="{% static 'assets/plugins/toastr/toastr-config.js' %}" ></script>

<!-- Custom js -->
<script src="{% static 'assets/js/custom.js' %}"></script>

<!-- Switcher js -->
<script src="{% static 'assets/switcher/js/switcher-rtl.js' %}"></script>
{% endblock js %}

{% block domready %}
<script>
    $(function () {
        $("#table").DataTable({
            "responsive": true,
            "autoWidth": false,
            "rtl" : true,
            "language": {
                "paginate": {
                    "previous": "قبلی",
                    "next" : "بعدی"
                },
                "sLengthMenu": "تعداد رکورد در صفحه _MENU_ ",
                "sSearch" : "جستجو:",
                "emptyTable":     "هیچ داده ای برای نمایش موجود نیست",
                "info":           "نمایش _START_ تا _END_ از _TOTAL_ رکورد",
                "infoEmpty":      "نمایش 0 تا 0 از 0 رکورد",

                "infoFiltered":   "(نتیجه جستجو بین _MAX_ رکورد)",
                "zeroRecords":    "اطلاعاتی مبنی بر جستجو شما موجود نیست...",
            },



        });
    });
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })

	$(function(){
		$("ul.pagination").css("justify-content", "start")
	});
</script>

{% include 'includes/messages.html' %}
{% endblock domready %}