accounts/urls.py
from django.urls import (
	path,
	include,
)
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"

urlpatterns = [
	path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),
				   name="login"),
	path("signup/", views.signup, name="signup"),


	path("password_change/",
		 auth_views.PasswordChangeView.as_view(
			template_name="accounts/password_change_form.html"), 
		 name="password_change"
    ),
    path("password_change/done/",
         auth_views.PasswordChangeDoneView.as_view(
			template_name="accounts/password_change_done.html"),
         name="password_change_done",
    ),

	
    path("password_reset/", 
		 auth_views.PasswordResetView.as_view(
			template_name="accounts/password_reset_form.html"),
		 name="password_reset"),
    path("password_reset/done/",
         auth_views.PasswordResetDoneView.as_view(
			template_name="accounts/password_reset_done.html"),
         name="password_reset_done",
    ),
    path("reset/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(
			template_name="accounts/password_reset_confirm.html"),
         name="password_reset_confirm",
    ),
    path("reset/done/",
         auth_views.PasswordResetCompleteView.as_view(
			template_name="accounts/password_reset_complete.html"),
         name="password_reset_complete",
    ),
	
	path("", include("django.contrib.auth.urls")),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
	path('accounts/', include("django.contrib.auth.urls")),
	path('panel/', include("panel.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("home.urls")),
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
	path('', views.index, name="index"),
]

panel/urls.py
from django.urls import path
from . import views

app_name = "panel"
urlpatterns = [
	path("home/", views.index, name="home"),
	path("profile/", views.profile, name="profile"),
	path("profile/avatar/", views.update_remove_avatar, name="update_remove_avatar"),

	# users
	path("users/", views.users_list, name="users_list"),
	path("users/create/", views.create_user, name="create_user"),
	path("users/update/<int:id>/", views.update_user, name="update_user"),
	path("users/delete/<int:id>/", views.delete_user, name="delete_user"),

	# management
	path("admin/users/", views.management_users_list, name="management_users_list"),
	path("admin/users/create/", views.create_staff_user, name="create_staff_user"),
	path("admin/users/update/<int:id>/", views.update_staff_user, name="update_staff_user"),
	path("admin/users/delete/<int:id>/", views.delete_staff_user, name="delete_staff_user"),
	path("admin/roles/", views.roles_list, name="roles_list"),
	path("admin/roles/create/", views.create_role, name="create_role"),
	path("admin/roles/update/<int:id>/", views.update_role, name="update_role"),
	path("admin/roles/delete/<int:id>/", views.delete_role, name="delete_role"),
	path("admin/categories/", views.categories_list, name="categories_list"),
	path("admin/categories/create/", views.create_category, name="create_category"),
	path("admin/categories/update/<int:id>/", views.update_category, name="update_category"),
	path("admin/categories/delete/<int:id>/", views.delete_category, name="delete_category"),
	path("settings/website/", views.website_settings, name="website_settings"),
	path("settings/aboutus/", views.aboutus_settings, name="aboutus_settings"),
	path("settings/contactus/", views.contactus_settings_list, name="contactus_settings_list"),
]

accounts/models.py
import os
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator
from django.utils.translation import gettext as _
from utils.general_model import GeneralModel
from .managers import CustomUserManager

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '%s.%s' %(uuid.uuid4(), ext)
    return os.path.join(f'users/', filename)


class CustomUser(AbstractUser, GeneralModel):
	first_name = None
	last_name = None
	full_name = models.CharField(max_length=128,
								 verbose_name=_("Full name"),)
	nick_name = models.CharField(max_length=128,
								 verbose_name=_("Nick name"),)
	email = models.EmailField(unique=True,
							  verbose_name=_("Email address"),)
	phone = models.CharField(max_length=13,
							 validators=[MinLengthValidator(10)],
							 blank=True,
							 null=True,
							 verbose_name=_("Phone"),)
	address = models.CharField(max_length=512,
							   blank=True,
							   null=True,
							   verbose_name=_("Address"),)
	avatar = models.ImageField(upload_to=get_file_path,
							   null=True,
							   blank=True,
							   verbose_name=_("Image profile"),)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	class Meta:
		verbose_name = "user"
		verbose_name_plural = "users"
		permissions = (("can_manage_staff_users", "Can manage staff users"),
					   ("can_manage_simple_users", "Can manage simple users"),
					   ("can_manage_categories", "Can manage categories"),
					   ("can_manage_website_settings", "Can manage website settings"),)

	objects = CustomUserManager()

	def __str__(self):
		return self.email

accounts/forms.py
from django import forms
from django.utils.translation import gettext as _
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import (
	UserCreationForm,
	UserChangeForm,
)
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
	password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(),
		validators=[validate_password],)
	password2 = None
	
	class Meta:
		model = CustomUser
		fields = ("email", "full_name")


class CustomUserChangeForm(UserChangeForm):
	
	class Meta:
		model = CustomUser
		fields = ("email",)

accounts/views.py
from django.shortcuts import (
	render,
	redirect,
)
from django.contrib import messages
from django.contrib.auth.signals import user_logged_in
from django.utils.translation import gettext as _
from django.contrib.auth import (
	login,
	authenticate,
)
from .forms import (
	CustomUserCreationForm,
)


def signup(request):
	if request.method == "POST":
		form = CustomUserCreationForm(request.POST)
		if form.is_valid():
			email = form.cleaned_data.get("email")
			full_name = form.cleaned_data.get("full_name")
			raw_password = form.cleaned_data.get("password1")
			form = form.save(commit=False)
			form.username = email
			form.nick_name = full_name
			form.save()
			user = authenticate(email=email, password=raw_password)
			login(request, user)
			message_text = _(f"حساب کاربری شما با موفقیت ساخته شد. لطفا ایمیل خود را تایید کنید.")
			messages.success(request, message_text)
			return redirect("/")
		else:
			if form.errors.get('email'):
				for err in form.errors.get('email'):
					message_text = _(err)
					messages.error(request, message_text)
			elif form.errors.get('password1'):
				for err in form.errors.get('password1'):
					message_text = _(err)
					messages.error(request, message_text)

	else:
		form = CustomUserCreationForm()
	return render(request,
				  "accounts/signup.html",
				  {"form": form,})

def logged_in_message(sender, user, request, **kwargs):
	messages.info(request, f"{request.user.nick_name} عزیز خوش آمدید:)")

user_logged_in.connect(logged_in_message)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load replace_halfspace %}


{% block title %}
ورود
{% endblock title %}


{% block css %}
<!-- Bootstrap css-->
<link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>

<!-- Icons css-->
<link href="{% static 'assets/plugins/web-fonts/icons.css' %}" rel="stylesheet"/>
<link href="{% static 'assets/plugins/web-fonts/font-awesome/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/plugins/web-fonts/plugin.css' %}" rel="stylesheet"/>

<!-- Style css-->
<link href="{% static 'assets/css-rtl/style/style.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/skins.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/dark-style.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/colors/default.css' %}" rel="stylesheet">

<!-- Color css-->
<link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css-rtl/colors/color.css' %}">

<!-- Toastr css -->
<link href="{% static 'assets/plugins/toastr/toastr.min.css' %}" rel="stylesheet">

<!-- Switcher css-->
<link href="{% static 'assets/switcher/css/switcher-rtl.css' %}" rel="stylesheet">
<link href="{% static 'assets/switcher/demo.css' %}" rel="stylesheet">
{% endblock css %}


{% block main-body %}

{% block page %}
<!-- Page -->
<div class="page main-signin-wrapper">
	<!-- Row -->
	<div class="row signpages text-center">
		<div class="col-md-12">
			<div class="card">
				<div class="row row-sm">
					<div class="col-lg-6 col-xl-5 d-none d-lg-block text-center bg-primary details">
						<div class="mt-5 pt-4 p-2 pos-absolute">
							{% comment %} <img src="{% static 'assets/img/brand/logo-light.png' %}" class="header-brand-img mb-4" alt="logo"> {% endcomment %}
							<div class="clearfix"></div>
							<img src="{% static 'assets/img/svgs/user.svg' %}" class="ht-100 mb-0" alt="user">
							<h5 class="mt-4 text-white">حساب کاربری برای خود بسازید</h5>
							<span class="tx-white-6 tx-13 mb-5 mt-xl-0">برای ایجاد ، کشف و ارتباط با جامعه جهانی ثبت نام کنید</span>
						</div>
					</div>
					<div class="col-lg-6 col-xl-7 col-xs-12 col-sm-12 login_form ">
						<div class="container-fluid">
							<div class="row row-sm">
								<div class="card-body mt-2 mb-2">
									<img src="{% static 'assets/img/brand/logo.png' %}" class=" d-lg-none header-brand-img text-left float-left mb-4" alt="logo">
									<div class="clearfix"></div>
									<form method="post">
										<h5 class="text-right mb-2">به حساب خود وارد شوید</h5>
										<p class="mb-4 text-muted tx-13 ml-0 text-right">برای ایجاد ، کشف و ارتباط با جامعه جهانی وارد سیستم شوید</p>
										<div class="form-group text-right">
											<label for="id_username">پست الکترونیک</label>
											{% render_field form.username type="email" class+="form-control" placeholder="ایمیل خود را وارد کنید" %}
										</div>
										<div class="form-group text-right">
											<label for="id_password">کلمه عبور</label>
											{% render_field form.password class+="form-control" placeholder="رمز ورود خود را وارد کنید" %}
										</div>
										{% csrf_token %}
										<button class="btn ripple btn-main-primary btn-block" type="submit">ورود</button>
									</form>
									<div class="text-right mt-5 ml-0">
										<div class="mb-1"><a href="{% url 'accounts:password_reset' %}">رمز عبور خود را فراموش کرده اید؟</a></div>
										<div>حساب ندارید؟ <a href="{% url 'accounts:signup' %}">اینجا ثبت نام کنید</a></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Row -->
</div>
<!-- End Page -->
{% endblock page %}

{% endblock main-body %}

{% block back-to-top %}
{% endblock back-to-top %}

{% block js %}
<!-- Jquery js-->
<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap js-->
<script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Select2 js-->
<script src="{% static 'assets/plugins/select2/js/select2.min.js' %}"></script>

<!-- Toastr js -->
<script src="{% static 'assets/plugins/toastr/toastr.min.js' %}" ></script>
<script src="{% static 'assets/plugins/toastr/toastr-config.js' %}" ></script>

<!-- Custom js -->
<script src="{% static 'assets/js/custom.js' %}"></script>

<!-- Switcher js -->
<script src="{% static 'assets/switcher/js/switcher-rtl.js' %}"></script>
{% endblock js %}

{% block domready %}
{% for key, errors in form.errors.items %}
	{% for err in errors %}
	<script>toastr.error("{{ err|replace_halfspace|linebreaksbr }}");</script>
	{% endfor %}
{% endfor %}
{% endblock domready %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}
فراموشی رمز عبور
{% endblock title %}


{% block css %}
<!-- Bootstrap css-->
<link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>

<!-- Icons css-->
<link href="{% static 'assets/plugins/web-fonts/icons.css' %}" rel="stylesheet"/>
<link href="{% static 'assets/plugins/web-fonts/font-awesome/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/plugins/web-fonts/plugin.css' %}" rel="stylesheet"/>

<!-- Style css-->
<link href="{% static 'assets/css-rtl/style/style.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/skins.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/dark-style.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/colors/default.css' %}" rel="stylesheet">


<!-- Color css-->
<link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css-rtl/colors/color.css' %}">

<!-- Switcher css-->
<link href="{% static 'assets/switcher/css/switcher-rtl.css' %}" rel="stylesheet">
<link href="{% static 'assets/switcher/demo.css' %}" rel="stylesheet">
{% endblock css %}


{% block main-body %}

{% block page %}
<!-- Page -->
<div class="page main-signin-wrapper">

	<!-- Row -->
	<div class="row signpages text-center">
		<div class="col-md-12">
			<div class="card">
				<div class="row row-sm">
					<div class="col-lg-6 col-xl-5 d-none d-lg-block text-center bg-primary details">
						<div class="mt-3 pt-3 p-2 pos-absolute">
							{% comment %} <img src="{% static 'assets/img/brand/logo-light.png' %}" class="header-brand-img mb-4" alt="logo"> {% endcomment %}
							<div class="clearfix"></div>
							<img src="{% static 'assets/img/svgs/user.svg' %}" class="ht-100 mb-0" alt="user">
							<h5 class="mt-4 text-white">گذرواژه خود را بازنشانی کنید</h5>
							<span class="tx-white-6 tx-13 mb-5 mt-xl-0">برای ایجاد ، کشف و ارتباط با جامعه جهانی ثبت نام کنید</span>
						</div>
					</div>
					<div class="col-lg-6 col-xl-7 col-xs-12 col-sm-12 login_form ">
						<div class="container-fluid">
							<div class="row row-sm">
								<div class="card-body mt-2 mb-2">
									<img src="{% static 'assets/img/brand/logo.png' %}" class=" d-lg-none header-brand-img text-left float-left mb-4" alt="logo">
									<div class="clearfix"></div>
									<h5 class="text-right mb-2">رمز عبور را فراموش کرده اید</h5>
									<p class="mb-4 text-muted tx-13 ml-0 text-right">ثبت نام رایگان است و فقط یک دقیقه طول می کشد.</p>
									<form method="post">
										<div class="form-group text-right">
											<label for="id_email">پست الکترونیک</label>
											{% render_field form.email class+="form-control" placeholder="ایمیل خود را وارد کنید" value="" %}
										</div>
										{% csrf_token %}
										<button class="btn ripple btn-main-primary btn-block">پیوند تنظیم مجدد را درخواست کنید</button>
									</form>
									<div class="card-footer border-top-0 pr-0 mt-3 text-right">
										<p>آیا رمز عبور خود را به یاد آوردید؟</p>
										<p class="mb-0">سعی کنید <a href="{% url 'accounts:login' %}">ورود</a></p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Row -->

</div>
<!-- End Page -->
{% endblock page %}

{% endblock main-body %}


{% block back-to-top %}
{% endblock back-to-top %}


{% block js %}
<!-- Jquery js-->
<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap js-->
<script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Select2 js-->
<script src="{% static 'assets/plugins/select2/js/select2.min.js' %}"></script>

<!-- Custom js -->
<script src="{% static 'assets/js/custom.js' %}"></script>

<!-- Switcher js -->
<script src="{% static 'assets/switcher/js/switcher-rtl.js' %}"></script>
{% endblock js %}

{% block domready %}
{% endblock domready %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
ثبت نام
{% endblock title %}

{% block css %}
<!-- Bootstrap css-->
<link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>

<!-- Icons css-->
<link href="{% static 'assets/plugins/web-fonts/icons.css' %}" rel="stylesheet"/>
<link href="{% static 'assets/plugins/web-fonts/font-awesome/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/plugins/web-fonts/plugin.css' %}" rel="stylesheet"/>

<!-- Style css-->
<link href="{% static 'assets/css-rtl/style/style.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/skins.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/dark-style.css' %}" rel="stylesheet">
<link href="{% static 'assets/css-rtl/colors/default.css' %}" rel="stylesheet">

<!-- Color css-->
<link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css-rtl/colors/color.css' %}">

<!-- Toastr css -->
<link href="{% static 'assets/plugins/toastr/toastr.min.css' %}" rel="stylesheet">

<!-- Switcher css-->
<link href="{% static 'assets/switcher/css/switcher-rtl.css' %}" rel="stylesheet">
<link href="{% static 'assets/switcher/demo.css' %}" rel="stylesheet">
{% endblock css %}


{% block main-body %}

{% block page %}
<!-- Page -->
<div class="page main-signin-wrapper">

	<!-- Row -->
	<div class="row signpages text-center">
		<div class="col-md-12">
			<div class="card">
				<div class="row row-sm">
					<div class="col-lg-6 col-xl-5 d-none d-lg-block text-center bg-primary details">
						<div class="mt-5 pt-5 p-2 pos-absolute">
							{% comment %} <img src="{% static 'assets/img/brand/logo-light.png' %}" class="header-brand-img mb-4" alt="logo"> {% endcomment %}
							<div class="clearfix"></div>
							<img src="{% static 'assets/img/svgs/user.svg' %}" class="ht-100 mb-0" alt="user">
							<h5 class="mt-4 text-white">حساب کاربری برای خود بسازید</h5>
							<span class="tx-white-6 tx-13 mb-5 mt-xl-0">برای ایجاد ، کشف و ارتباط با جامعه جهانی ثبت نام کنید</span>
						</div>
					</div>
					<div class="col-lg-6 col-xl-7 col-xs-12 col-sm-12 login_form ">
						<div class="container-fluid">
							<div class="row row-sm">
								<div class="card-body mt-2 mb-2">
									{% comment %} <img src="{% static 'assets/img/brand/logo.png' %}" class=" d-lg-none header-brand-img text-left float-left mb-4" alt="logo"> {% endcomment %}
									<div class="clearfix"></div>
									<h5 class="text-right mb-2">ثبت نام رایگان</h5>
									<p class="mb-4 text-muted tx-13 ml-0 text-right">ثبت نام رایگان است و فقط یک دقیقه طول می کشد.</p>
									<form method="post">
										<div class="form-group text-right">
											<label for="id_full_name">نام</label>
											{% render_field form.full_name class+="form-control" placeholder="اسمت را وارد کن" autofocus="autofocus" %}
										</div>
										<div class="form-group text-right">
											<label for="id_email">پست الکترونیک</label>
											{% render_field form.email class+="form-control" placeholder="ایمیل خود را وارد کنید" %}
										</div>
										<div class="form-group text-right">
											<label for="id_password1">کلمه عبور</label>
											{% render_field form.password1 class+="form-control" placeholder="رمز ورود خود را وارد کنید" %}
										</div>
										{% csrf_token %}
										<button class="btn ripple btn-main-primary btn-block">ثبت نام</button>
									</form>
									<div class="text-right mt-5 ml-0">
										<p class="mb-0">در حال حاضر یک حساب کاربری دارید <a href="{% url 'accounts:login' %}">ورود</a></p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Row -->

</div>
<!-- End Page -->
{% endblock page %}

{% endblock main-body %}


{% block back-to-top %}
{% endblock back-to-top %}


{% block js %}
<!-- Jquery js-->
<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap js-->
<script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Select2 js-->
<script src="{% static 'assets/plugins/select2/js/select2.min.js' %}"></script>

<!-- Toastr js -->
<script src="{% static 'assets/plugins/toastr/toastr.min.js' %}" ></script>
<script src="{% static 'assets/plugins/toastr/toastr-config.js' %}" ></script>

<!-- Custom js -->
<script src="{% static 'assets/js/custom.js' %}"></script>

<!-- Switcher js -->
<script src="{% static 'assets/switcher/js/switcher-rtl.js' %}"></script>
{% endblock js %}

{% block domready %}
{% include 'includes/messages.html' %}
{% endblock domready %}